// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SodaBox.DataAccess;

#nullable disable

namespace SodaBox.Migrations
{
    [DbContext(typeof(VendingMachineContext))]
    [Migration("20240914100342_InitialCreate-2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SodaBox.DataAccess.Entities.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("brands");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Coca Cola"
                        },
                        new
                        {
                            id = 2,
                            name = "Pepsi"
                        },
                        new
                        {
                            id = 3,
                            name = "Fanta"
                        },
                        new
                        {
                            id = 4,
                            name = "Sprite"
                        });
                });

            modelBuilder.Entity("SodaBox.DataAccess.Entities.Drink", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("int");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("drinks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            brandId = 1,
                            imagePath = "images/drinks/coca_cola.png",
                            name = "Coca Cola",
                            price = 1.99m,
                            quantity = 10
                        },
                        new
                        {
                            id = 2,
                            brandId = 2,
                            imagePath = "images/drinks/pepsi.png",
                            name = "Pepsi",
                            price = 1.89m,
                            quantity = 5
                        },
                        new
                        {
                            id = 3,
                            brandId = 1,
                            imagePath = "images/drinks/coca_cola_zero.png",
                            name = "Coca Cola Zero",
                            price = 2.19m,
                            quantity = 5
                        },
                        new
                        {
                            id = 4,
                            brandId = 3,
                            imagePath = "images/drinks/fanta.png",
                            name = "Fanta",
                            price = 1.55m,
                            quantity = 5
                        },
                        new
                        {
                            id = 5,
                            brandId = 4,
                            imagePath = "images/drinks/sprite.png",
                            name = "Sprite",
                            price = 1.89m,
                            quantity = 5
                        });
                });

            modelBuilder.Entity("SodaBox.DataAccess.Entities.Drink", b =>
                {
                    b.HasOne("SodaBox.DataAccess.Entities.Brand", "brand")
                        .WithMany("drinks")
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("SodaBox.DataAccess.Entities.Brand", b =>
                {
                    b.Navigation("drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
